### Внимание! Необходимо использовать функции numpy по-максимуму! И практически никаких циклов!


In [1]:
import numpy as np  

### 1. Отсортируйте содержимое матрицы по возрастанию:

In [2]:
np.random.seed(21)
A = np.random.randint(0, 10, (5, 3))
print(A)

[[9 8 4]
 [0 0 8]
 [3 2 1]
 [8 9 6]
 [0 4 6]]


In [3]:
A = np.sort(A)
print(A)

[[4 8 9]
 [0 0 8]
 [1 2 3]
 [6 8 9]
 [0 4 6]]


### 2. Найти наиболее частое значение в массиве

In [4]:
C = np.random.randint(0, 10, (5, 3))
print(C)
print("наиболее частое значение в массиве:", np.bincount(np.ravel(C)).argmax())

[[4 4 7]
 [8 9 5]
 [6 5 2]
 [6 2 8]
 [2 0 5]]
наиболее частое значение в массиве: 2


### 3. Найти n наибольших значений в массиве

In [9]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 12

In [10]:
Z_sort = np.sort(Z)[::-1]
print(Z_sort[:n])
    

[9999 9998 9997 9996 9995 9994 9993 9992 9991 9990 9989 9988]


### 4. Пусть задан некоторый массив  𝑋 . Заменить все элементы с нечетными индексами на число  𝑎  (если оно не указано, то на 1), четные - возвести в куб и записать в обратном порядке на те же позиции. Массив  𝑋  при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X.

Пример:
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [7]:
X = np.array([10, 20, 30, 40, 50])
# a = 77
X_changed = X.copy()
try:
    X_changed[1::2] = a
except:
    X_changed[1::2] = 1
X_changed[::2] = np.power(X_changed[::2], 3)
X_changed = np.flip(X_changed)
X = np.concatenate([X, X_changed])
print(X)


[    10     20     30     40     50 125000      1  27000      1   1000]


### 5. Создать два массива с 3-мя компонентами `a` и `b`. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.randint(0, 10, 3)
b = np.random.randint(0, 10, 3)
%timeit scalar_prod_np = np.dot(a, b)
%timeit scalar_prod = sum([a[i] * b[i] for i in range(len(a))])


1.44 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.35 µs ± 46.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
