###Внимание! Необходимо использовать функции numpy по-максимуму! И практически никаких циклов!


In [1]:
import numpy as np

### 1. Отсортируйте содержимое матрицы, чтобы в каждом столбце все значения распологались по возрастанию:

In [2]:
np.random.seed(21)
a = np.random.randint(0, 10, (5, 3))
print(a)

[[9 8 4]
 [0 0 8]
 [3 2 1]
 [8 9 6]
 [0 4 6]]


In [3]:
a_sorted = np.sort(a, axis=0)
print(a_sorted)

[[0 0 1]
 [0 2 4]
 [3 4 6]
 [8 8 6]
 [9 9 8]]


### 2. Найти наиболее частое значение в массиве

In [4]:
print("наиболее частое значение в массиве:", np.bincount(np.ravel(a)).argmax())


наиболее частое значение в массиве: 0


### 3. Найти n наибольших значений в массиве

In [5]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [6]:
Z_sort = np.sort(Z)[::-1]
print(Z_sort[:n])
    

[9999 9998 9997 9996 9995]


### 4. Дан двумерный массив. Найти все различные строки

In [7]:
Z = np.random.randint(0, 2, (6,3))
print(Z)

[[1 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 0]
 [1 1 0]
 [0 0 1]]


In [8]:
Z_unique = np.unique(Z, axis=0)
print(Z_unique)


[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]]


### 5. Дан массив arr, необходимо найти среднее значение внутри групп, группа определена массивом g. 
Например, для  
`arr = [4, 2, 1, 5, 2, 5, 1, 3]` и   
`g =   [0, 1, 1, 0, 1, 0, 1, 0]` (4 относится к группе 0, 2 к группе 1 и т. д.)   
Средние по группам: `[4.25, 1.5]`  
Подсказка: `np.bincount()`   
Используйте библиотеку `numpy`, не используйте циклы.

In [9]:
arr = np.array([4, 2, 1, 5, 2, 5, 1, 3])
g = np.array([0, 1, 1, 0, 1, 0, 1, 0])
el_count = np.bincount(g)
sum_in_group = np.bincount(g, arr)
avg_in_group = sum_in_group / el_count
print(avg_in_group)

[4.25 1.5 ]


### 6. Перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним. Сравнить время вычислений



In [25]:
A = np.random.randint(0, 20, (5, 5))
B = np.random.randint(0, 20, (5, 5))

def matrix_prod_py(a, b):
    C_py = [[0 for row in range(len(A))] for col in range(len(B))]
    for i in range(len(A)):
        for j in range(len(B)):
            for k in range(len(A)):
                C_py[i][j] += A[i][k] * B[k][j]
    return C_py

print('без numpy')
# print(*matrix_prod_py(A, B), sep='\n')
%timeit matrix_prod_py(A, B)
print('с numpy')
# print(np.dot(A, B))
%timeit np.dot(A, B)

без numpy
82.2 µs ± 2.12 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
с numpy
1.64 µs ± 42.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### 7. Написать функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость.

In [16]:
n = 20
a = list(range(1, n+1))

def Sn_py(a):
    Sn = [sum(range(1, i+1))/i for i in a]
    return Sn

def Sn_numpy(a):
    a = np.array(a)
    Sn = np.divide(np.cumsum(a), a)
    return Sn

# print(Sn_py(a))
print('без numpy')
%timeit Sn_py(a)
# print(Sn_numpy(a))
print('с numpy')
%timeit Sn_numpy(a)

без numpy
9.05 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
с numpy
8.08 µs ± 1.05 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


на ряду из малого кол-ва эл-ов код на py быстрее кода на numpy, при увеличении кол-ва элементов ряда ситуация меняется на противоположную

### 8. Пусть задан некоторый массив  𝑋 . Заменить все элементы с нечетными индексами на число  𝑎  (если оно не указано, то на 1), четные - возвести в куб и записать в обратном порядке на те же позиции. Массив  𝑋  при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X.

Пример:
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [12]:
X = np.array([10, 20, 30, 40, 50])
# a = 77
X_changed = X.copy()
try:
    X_changed[1::2] = a
except:
    X_changed[1::2] = 1
X_changed[::2] = np.power(X_changed[::2], 3)
X_changed = np.flip(X_changed)
X = np.concatenate([X, X_changed])
print(X)


[    10     20     30     40     50 125000      1  27000      1   1000]


### 9. Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [17]:
a = np.random.randint(-5, 10, size=3)
b = np.random.randint(-5, 10, size=3)

def scalar_prod_py(a, b):
    prod = 0
    for i in range(len(a)):
        prod += a[i] * b[i]
    return prod

print('без numpy:')
# print(scalar_prod_py(a, b))
%timeit scalar_prod_py(a, b)
print('c numpy:')
# print(np.dot(a, b))
%timeit np.dot(a, b)

без numpy:
1.18 µs ± 66 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
c numpy:
1.37 µs ± 42.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### 10. Написать решето Эратосфена с Numpy. Минимум циклов!

In [18]:
n = 211
a = np.arange(2, n+1)
b = np.full(n-1, fill_value=True)
for i in range(2, int(np.sqrt(n))+1):
    b[np.where((a != i) & (a % i == 0))] = False
print(a[b])

[  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149 151
 157 163 167 173 179 181 191 193 197 199 211]


### 11. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. 
Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5

In [19]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(np.max(x[np.array(np.where(x[:-1]==0)) + 1]))

5
